### ISSUE TITLE
why do the examples still reference PIXI.Stage?

### ISSUE THREAD

**Issue by mreinstein** [pixijs/examples#1]
I thought these examples are for v3

**Comment by englercj** [comment]
They are, I think @alvinsight was getting them to work (using compat layers) without rewriting them all. But since these are used as the "v3 way of doing things" we really shouldn't use deprecated features, and they wont when we are done with them.

There is still heavy development going on in this repo.

**Comment by ghost** [comment]
Yep, it was exactly this, I'll push a new version of the examples using our new format shortly, watch this space :)

**Comment by englercj** [comment]
@alvinsight Can you repush to `master`? I was in the middle of merging/cleaning branches when you just pushed that and `refactor` was deleted like the second after you pushed.

Something like this:

```
git checkout master && git pull origin master && git merge refactor && git push origin master
```

So your local changes to refactor make it up here. Thanks!
