### ISSUE TITLE
We made a wrong move

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/examples#25]
#24 just nuked examples for all version prior to 4.3.3

**Comment by themoonrat** [comment]
No pixi application, no previous examples.

I think it's a fair trade off and we should ditch being able to use any previous tagged version

**Comment by ivanpopelyshev** [comment]
Creating new plugin, "pixi-legacy", allows run new examples on older versions of pixijs

**Comment by clark-stevenson** [comment]
> ditch being able to use any previous tagged version

What was the point in that option?  Just wondered, I see them sometimes on some projects, and wonder what the use case is?

**Comment by bigtimebuddy** [comment]
Examples are not about maintaining legacy and compatibility. If they are, we should manage the history in a better way. However, examples are getting newbies on-boarded quicker. Someone that uses v3 or a specific version should know enough to not require examples and demos. Examples should always be for the latest release.

**Comment by ivanpopelyshev** [comment]
@clark-stevenson @bigtimebuddy I'm using it too test every major change. People use it too.

so, my new project, "pixi-legacy" will be able to upgrade old versions with hacks, and downgrade new ones too. It's supposed to be enabled in examples for all versions behind release.

**Comment by themoonrat** [comment]
To easily compete how over version worked compared to another.

"I think version x introduced a bug"
"Ok, it actually change how it worked on version x.x"

I like a compatibility layer for examples that ivan suggested

**Comment by ivanpopelyshev** [comment]
https://github.com/ivanpopelyshev/pixi-legacy

**Comment by clark-stevenson** [comment]
Thanks guys,  I understand why that might be helpful but why, as a consumer, I don't really use tags.  I kind of agree with Matt due to that Bias.  

Anyway I don't speak often, but kudos on the big examples PR ticket.  I was stuck with a ripped V3 test which was probably 18 months old and I pretended it wasn't there because the examples confused me.  I spent most of today re-writing that to match that PR.  I appreciate the work that went into it which why I would hate to see it lost.  Also `Application` is a great addition.  It is amazing to `extend Application` and get rid of all the pish.

Ivan's new readme made me laugh, Most of my updates are a Friday Night and he knows. 👍

**Comment by staff0rd** [comment]
What I need is an easy way to switch pixi versions against a pen.

**Comment by bigtimebuddy** [comment]
Examples and use-cases to test against are two entirely different objectives. We need a better test suite for verifying changes. Like what bunnymark is for performance. Examples should not be that. I propose we build something new designed to just test features and is robust and comprehensive.
